name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  compile:
    name: Compile rootfs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies for build (Apt)
        run: |
          sudo env DEBIAN_FRONTEND=noninteractive apt update -y && \
          sudo env DEBIAN_FRONTEND=noninteractive apt install -y libarchive-tools
      - name: Build
        run: |
          make
          make clean
